inputs_def:
  - handle: epub_file_path
    json_schema:
      type: string
      ui:widget: file
  - handle: output_path
    json_schema:
      type: string
      ui:widget: dir
    nullable: true
    value:
outputs_def:
  - handle: output_path
    json_schema:
      type: string
      ui:widget: dir
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Extract spines from epub book
