inputs_def:
  - handle: fragments
    description: Input
    json_schema:
      type: array
      items:
        type: string
  - handle: save_dir_path
    json_schema:
      type: string
      ui:widget: dir
  - handle: title
    json_schema:
      type: string
    nullable: true
    value:
outputs_def:
  - handle: text
    description: Output
    json_schema:
      type: string
  - handle: audio_path
    json_schema:
      type: string
      ui:widget: file
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Generate speech tasks
